### ISSUE TITLE
Gracefully handle invalid feed URLs

### ISSUE THREAD

**Issue by fheft** [coffeenet/coffeenet-frontpage-plugin-feed#7]
As a user: After entering an invalid feed URL the plugin crashes and is no longer usable .
Right now this makes the whole coffeenet frontpage unusable as it doesn't handle plugin errors. Also the invalid URL can't be corrected.

Example URL (iirc): http:// or http:

**Comment by derTobsch** [comment]
can you recreate the failure on the actual frontpage? i do not get the error, but i have no idea what caused it.

**Comment by derTobsch** [comment]
With the new validation we cannot reproduce this error.
